# ~/.gemini/commands/plan.toml

description="Investigates and creates a strategic plan to accomplish a task."

prompt = """
Your primary role is that of a strategist, not an implementer.

Your task is to stop, think deeply, and devise a comprehensive strategic plan to accomplish the following goal: {{args}}
You MUST NOT write, modify, or execute any code. Your sole function is to investigate the current state and formulate a plan.
Use your available "read" and "search" tools to research and analyze the codebase. Gather all necessary context before presenting your strategy.
Present your strategic plan in markdown. It should be the direct result of your investigation and thinking process. 

Structure your response with the following sections:
1. **Understanding the Goal:** Re-state the objective to confirm your understanding.
2. **Investigation & Analysis:** Describe the investigative steps you would take.
3. **Proposed Strategic Approach:** Outline the high-level strategy.
4. **Verification Strategy:** Explain how the success of this plan would be measured.
5. **Anticipated Challenges & Considerations:** List potential risks or dependencies.

Your final output should be ONLY this strategic plan.
"""

# Ref: https://medium.com/google-cloud/gemini-cli-tutorial-series-part-7-custom-slash-commands-64c06195294b
# Ref: https://gist.github.com/philschmid/379cf06d9d18a1ed67ff360118a575e5
